#!/bin/bash

#output
output=$HOME/research/sys_info.txt

#making a research directory
if [ ! -d $HOME/research ]
then
mkdir $HOME/research
fi

#Title & date
echo "A Quick System Audit Script" >> $output

#Today's date
date >> $output

#The machine's type
echo "Machine Type Info" >> $output
echo "MACHTYPE" >> $output

#Uname
echo -e "Uname info: $(uname -a) \n" >> $output

#Machine's IP Address
echo -e "IP Info:" >> $output
echo -e "$ip \n" >> $output
ip=$(ip addr | head -9 | tail -1)

#Hostname
echo "Hostname: $(hostname -s) " >> $output

#DNS Info
echo "DNS Servers: " >> $output
cat /etc/resolv.conf >> $output

#Memory Info
echo "Memory Info" >> $output
free >> $output

#CPU Info
echo -e "\nCPU Info" $output
lscpu | grep CPU $output

#Disk Usage
echo -e "\nDisk Usage" >> $output
df -H | head -2 >> $output

#Currently logged on users
echo -e "\nWho is logged on: $(who -a) \n" >> $output 

#Finding files that are 777
echo -e "\n777 files:" >> $output
execs=$(find / -type f -perm 777) >> $output

#Top 10 Processess
echo -e"\nTop 10 Processess" >> $output
ps -aux -m | awk -F {'print $1, $2, $3, $4, $11'} | head -11 >> $output


